apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: twilliams9397/docker_production_v3
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://mongo:27017/posts
          # command: [""] # deploy with this then delete and re deploy without
          # args: ["node","seeds/seed.js"] # error with seeds within the image before was pushed to docker
          imagePullPolicy: Always
          

---

apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
  resourceVersion: "40833"
  uid: 9190ab75-d61c-4ff4-a3d1-0d293fa8d72e
spec:
  # clusterIP: 
  # clusterIPs:
  # - 
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30442
    port: 80 # deploy to this port
    protocol: TCP
    targetPort: 3000 # listen to this port
  selector:
    app: node-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app
  namespace: default
spec:
  maxReplicas: 9
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app
  targetCPUUtilizationPercentage: 50












