apiVersion: batch/v1
kind: CronJob
metadata:
  name: eng89
spec:
  schedule: "*/1 * * * *" # will trigger job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: eng89
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo thank you for using cronjob
          restartPolicy: OnFailure

