# k8 works with API version to declare resources

# declaring deployment version
apiVersion: apps/v1
# type of resource  - case sensitive
kind: Deployment
# deployment info
metadata:
  name: nginx-deployment

# specification of deployment
spec:
  selector:
    # matches this resource that matches nginx
    matchLabels:
      app: nginx

  # create 2 replicas
  replicas: 2

  # template to use label for k8 service to launch in the browser
  template:
    metadata:
      labels:
        # must match above label
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80